"""
agents/report_agent.py

Reads the full PentestContext and generates a structured
Markdown report including the agent reasoning chain.
"""

from datetime import datetime
from pathlib import Path
from core.context import PentestContext, Severity
from core.report_render import compute_grade, render_html


SEVERITY_ORDER = {
    Severity.CRITICAL: 0,
    Severity.HIGH: 1,
    Severity.MEDIUM: 2,
    Severity.LOW: 3,
    Severity.INFO: 4,
}


def run_report(ctx: PentestContext, output_dir: str = "reports") -> str:
    ctx.log("report", f"Generating report. Total findings: {len(ctx.findings)}")

    grade, score = compute_grade(ctx.findings)
    ctx.grade = grade
    ctx.log("report", f"Security grade: {grade} ({score}/100)")

    sorted_findings = sorted(ctx.findings, key=lambda f: SEVERITY_ORDER[f.severity])

    critical = [f for f in sorted_findings if f.severity == Severity.CRITICAL]
    high = [f for f in sorted_findings if f.severity == Severity.HIGH]
    medium = [f for f in sorted_findings if f.severity == Severity.MEDIUM]
    low_info = [f for f in sorted_findings if f.severity in (Severity.LOW, Severity.INFO)]

    lines = []

    # Header
    lines += [
        "# redblue-agents Security Report",
        f"**Target:** {ctx.target_url}",
        f"**Security Grade:** {grade} ({score}/100)",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Tech Stack Detected:** {', '.join(ctx.tech_stack) or 'Unknown'}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"**{len(sorted_findings)} finding(s)** identified across {len(ctx.auth_vectors_tested)} tested vector(s).",
        "",
        _executive_narrative(ctx, sorted_findings),
        "",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| 🔴 Critical | {len(critical)} |",
        f"| 🟠 High | {len(high)} |",
        f"| 🟡 Medium | {len(medium)} |",
        f"| 🔵 Low/Info | {len(low_info)} |",
        "",
        "---",
        "",
        "## Findings",
        "",
    ]

    for i, finding in enumerate(sorted_findings, 1):
        emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFORMATIONAL": "⚪"}
        icon = emoji.get(finding.severity.value, "⚪")

        lines += [
            f"### {i}. {icon} [{finding.severity.value}] {finding.title}",
            "",
            f"**CVSS Score:** {finding.cvss_score} | **OWASP:** {finding.owasp_category}",
            "",
            f"**Description:** {finding.description}",
            "",
            f"**Evidence:**",
            f"```",
            finding.evidence,
            f"```",
            "",
            f"**Remediation:** {finding.remediation}",
            "",
            "---",
            "",
        ]

    # Security Headers Summary
    lines += [
        "## Security Headers",
        "",
        "| Header | Present | Notes |",
        "|--------|---------|-------|",
    ]
    for name, analysis in ctx.security_headers.items():
        status = "✅" if analysis.present else "❌"
        note = analysis.risk_note or (analysis.value[:60] if analysis.value else "—")
        lines.append(f"| {name} | {status} | {note} |")

    lines += ["", "---", ""]

    # CAPTCHA Analysis
    lines += [
        "## CAPTCHA Analysis",
        "",
        f"- **Detected:** {'Yes' if ctx.captcha_detected else 'No'}",
        f"- **Type:** {ctx.captcha_type.value}",
        f"- **Server-Side Enforcement:** {ctx.captcha_enforcement.value}",
        "",
        "---",
        "",
    ]

    # Rate Limiting
    rl = ctx.rate_limit_result
    if rl.tested:
        lines += [
            "## Rate Limiting",
            "",
            f"- **Requests sent:** {rl.requests_sent}",
            f"- **Block triggered:** {'Yes (at request #' + str(rl.block_at_request) + ')' if rl.block_triggered else 'No'}",
            f"- **Notes:** {rl.notes or '—'}",
            "",
            "---",
            "",
        ]

    # Claude reasoning notes (only when an API key was supplied)
    if ctx.llm_notes:
        lines += ["## Claude Reasoning", ""]
        for note in ctx.llm_notes:
            lines.append(f"- {note}")
        lines += ["", "---", ""]

    # Agent Reasoning Chain — the differentiator
    lines += [
        "## Agent Reasoning Chain",
        "",
        "*Full decision log from all agents during this run.*",
        "",
    ]
    for step in ctx.reasoning_chain:
        lines.append(f"- `[{step.agent}]` {step.message}")

    lines += ["", "---", ""]
    lines += [
        "*Generated by redblue-agents — for authorized security research only.*"
    ]

    report_md = "\n".join(lines)

    # Write Markdown + self-contained HTML
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    md_path = f"{output_dir}/report_{timestamp}.md"
    html_path = f"{output_dir}/report_{timestamp}.html"
    Path(md_path).write_text(report_md, encoding="utf-8")
    Path(html_path).write_text(render_html(ctx, grade, score), encoding="utf-8")

    ctx.log("report", f"Reports written: {md_path} and {html_path}")
    return html_path


def _executive_narrative(ctx: PentestContext, findings) -> str:
    """One-paragraph executive summary. Authored by Claude when available."""
    llm = ctx.llm
    fallback = (
        "Automated analysis completed. Review the findings below, prioritising "
        "Critical and High severity issues first."
        if findings else
        "No security issues were detected by the automated checks. This is not a "
        "guarantee of security — manual testing is still recommended."
    )
    if llm is None or not getattr(llm, "enabled", False):
        return fallback

    system = (
        "You are a senior application security consultant writing the executive "
        "summary of a pentest report. Be concise (3-5 sentences), factual, and "
        "business-oriented. Do not invent findings beyond those listed."
    )
    prompt = (
        f"Target: {ctx.target_url}\n"
        f"Tech stack: {ctx.tech_stack or 'unknown'}\n"
        "Findings:\n" + "\n".join(
            f"- [{f.severity.value}] {f.title} (CVSS {f.cvss_score})" for f in findings
        ) + ("\n(none)" if not findings else "")
    )
    text = llm.complete(system, prompt, max_tokens=400)
    return text or fallback
